version: "3.8"

services:
  backend:
    image: cloudy11/backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "8080:8080"
  frontend:
    image: cloudy11/frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend


